feat: [Improvement] Adds patches to k8s and docker environment config
overhangio/tutor-forum pull request #24
Opened 2023-07-31 13:02 UTC by xitij2000

The forum service is entirirely configured using environemnt variables, and there are a number of environment variables that are not configurable via tutor currently. This change adds patches in those places allowing additional configuration variables to be passed.

2023-07-31 14:36 UTC, regisb commented
I understand the need to configure the forum via environment variables. I really wish there was a better way to override environment variables than to implement multiple patches, but I thought about it long and hard and did not find a very elegant solution. This PR shows that there is already quite a bit of duplication in the forum templates.

2023-07-31 14:48 UTC, regisb commented
I think I got a better idea:

```
FORUM_ENV = tutor.core.hooks.Filter()
FORUM_ENV.add_items([
    ("SEARCH_SERVER", "{{ ELASTICSEARCH_SCHEME }}://{{ ELASTICSEARCH_HOST }}:{{ ELASTICSEARCH_PORT }}"),
    ...
])

@tutor.hooks.Filters.ENV_PATCHES.add()
def _forum_patches(patches):
    k8s_env_patch = ""
    local_env_patch = ""
    for key, value in FORUM_ENV.iterate():
        k8s_env_patch += f"- name: {key}\n  value: {value}\n"
        local_env_patch += f"{key}: {value}\n"
    patches += [("forum-k8s-env", k8s_env_patch), ("forum-local-env", local_env_patch)]
    return patches
```

And then in the k8s templates:

```
env:
    {{ patch("forum-k8s-env")|indent(12) }}
```

(and similar in the docker-compose templates)

With this approach, users would only have to add items to the `FORUM_ENV` filter to define new environment values. Moreover, this would remove a lot of duplication between forum templates.

Please tell me whether this makes sense, I understand it might be a little confusing.

2023-08-01 02:25 UTC, xitij2000 commented
> I think I got a better idea:
> 
> ```
> FORUM_ENV = tutor.core.hooks.Filter()
> FORUM_ENV.add_items([
>     ("SEARCH_SERVER", "{{ ELASTICSEARCH_SCHEME }}://{{ ELASTICSEARCH_HOST }}:{{ ELASTICSEARCH_PORT }}"),
>     ...
> ])
> 
> @tutor.hooks.Filters.ENV_PATCHES.add()
> def _forum_patches(patches):
>     k8s_env_patch = ""
>     local_env_patch = ""
>     for key, value in FORUM_ENV.iterate():
>         k8s_env_patch += f"- name: {key}\n  value: {value}\n"
>         local_env_patch += f"{key}: {value}\n"
>     patches += [("forum-k8s-env", k8s_env_patch), ("forum-local-env", local_env_patch)]
>     return patches
> ```
> 
> And then in the k8s templates:
> 
> ```
> env:
>     {{ patch("forum-k8s-env")|indent(12) }}
> ```
> 
> (and similar in the docker-compose templates)
> 
> With this approach, users would only have to add items to the `FORUM_ENV` filter to define new environment values. Moreover, this would remove a lot of duplication between forum templates.
> 
> Please tell me whether this makes sense, I understand it might be a little confusing.

I think this makes a lot more sense! I was just reluctant to add new config to the main project. 
Here, instead of using a patch though, wouldn't it be better to just directly iterate over `FORUM_ENV` in the templates?

2023-08-01 03:54 UTC, xitij2000 commented
Just realised what I proposed won't work since the values won't be rendered. So I've implemented your approach.

2023-08-01 04:29 UTC, xitij2000 commented
I generated the config with and without this change and here is the diff:

![tutor-forum-pr-24](https://github.com/overhangio/tutor-forum/assets/118837/298f6c80-f978-4781-8f13-e79fbb62e897)

So nothing that should break anything.

2023-08-02 16:54 UTC, xitij2000 commented on tutorforum/plugin.py
> +}
@regisb I decided to make it a dict instead of a list of tuples since this makes overriding individual environment variables simpler.

2023-08-02 17:16 UTC, gabor-boros commented
👍 @xitij2000

2023-08-03 09:24 UTC, regisb requested changes
I only have a couple minor comments, otherwise I think this is top notch. @ghassanmas what do you think?

2023-08-03 09:24 UTC, regisb commented on tutorforum/hooks.py
> +from tutor.core.hooks import Filter
I think you need to add `from __future__ import annotations` to get this to run on Python 3.8.

2023-08-03 09:24 UTC, regisb commented on tutorforum/plugin.py
> +def _forum_env_patches(patches):
This is a valid approach but it's uncommon, would you mind adding a comment to explain what is going on?

2023-08-03 13:31 UTC, xitij2000 commented on tutorforum/plugin.py
> +def _forum_env_patches(patches):
Sure, I've added comments and docstrings to explain what's going on here.

2023-08-04 16:14 UTC, ghassanmas commented on tutorforum/plugin.py
> +    "SEARCH_SERVER": "{{ ELASTICSEARCH_SCHEME }}://{{ ELASTICSEARCH_HOST }}:{{ ELASTICSEARCH_PORT }}",
This line got me an error when trying to test it locally with python 3.8  (which is included in `setup.py` )
When I tried to quickly test it I got the following error 
```
    FORUM_ENV_BASE: dict[str,str] = {
TypeError: 'type' object is not subscriptable
```
I think you might just need to import the type

2023-08-04 16:26 UTC, ghassanmas commented
This looks interesting change, I have quickly tested and provided a comment above... I will keep an eye on this and expect me to test it locally with docker/compose.  But I wouldn't test it with k8s as it's still a black box to me. 

A curious quesiotn I have; What would happen if opreator would use the k8s/local patch directly? like do we expect them to do so? _I suppose it might be the case if I have different configruation between local and k8s_

Another thing that also make the situation more obscure to me is that it might be the case that we run _k8s locally_ hence
-  openedx/wg-devops/issues/4 

But this I guess then something related to tutor core naming as always naming might not reflect the meaning :-)

2023-08-05 04:35 UTC, xitij2000 commented on tutorforum/plugin.py
> +    "SEARCH_SERVER": "{{ ELASTICSEARCH_SCHEME }}://{{ ELASTICSEARCH_HOST }}:{{ ELASTICSEARCH_PORT }}",
Iv'e added a `from __future__ import annotations` to the plugin.py file as well, which should fix this.

2023-08-05 04:43 UTC, xitij2000 commented
> This looks interesting change, I have quickly tested and provided a comment above... I will keep an eye on this and expect me to test it locally with docker/compose. But I wouldn't test it with k8s as it's still a black box to me.
> 
> A curious quesiotn I have; What would happen if opreator would use the k8s/local patch directly? like do we expect them to do so? _I suppose it might be the case if I have different configruation between local and k8s_
> 
> Another thing that also make the situation more obscure to me is that it might be the case that we run _k8s locally_ hence
> 
>     * [How to run Open edX on a local Kubernetes cluster? openedx/wg-devops#4](https://github.com/openedx/wg-devops/issues/4)
> 
> 
> But this I guess then something related to tutor core naming as always naming might not reflect the meaning :-)

I can't think for a good reason right now for someone to want different environment variables for k8s vs local. However, they can just use the patches in that case as you mentioned. 

I imagine people will generally only deploy an instance using local or k8s and not both from a single config, so if they wanted they can just copy over the config, change the required variables/plugins/settings and deploy to local and k8s from different configs.

I think running k8s on your local computer is a kind of an edge case! I've tested tutor again minikube and I currently run a k8s cluster on a secondary mini-pc exactly for these kinds of tests. I've had success so far, but it definitely takes some effort setting up.

2023-08-08 14:51 UTC, ghassanmas commented
I have tested this locally and it worked as expected, the services init, craeted a thread..etc. The only thing I can think of, is just ot update the readme, and second regarding the order/priority of the patches, my thinking is that we have know three pathces that can override each other: 
1. The forum built-in patch _that is filled_ from tutor config 
2. The forum env base 
3. The local/k8s variants 

My understanding and I think that the logical is tha should be loaded in that order, but I haven't tested that yet, looking through the code I see that 2 and 3 has priority high, so I think we should be safe... _unless we get into a weired edge case if opreator are using both 2 and 3 and 3 get loaded before 2_

2023-08-09 07:37 UTC, xitij2000 commented
> I have tested this locally and it worked as expected, the services init, craeted a thread..etc. The only thing I can think of, is just ot update the readme, and second regarding the order/priority of the patches, my thinking is that we have know three pathces that can override each other:
> 
>     1. The forum built-in patch _that is filled_ from tutor config
> 
>     2. The forum env base
> 
>     3. The local/k8s variants
> 
> 
> My understanding and I think that the logical is tha should be loaded in that order, but I haven't tested that yet, looking through the code I see that 2 and 3 has priority high, so I think we should be safe... _unless we get into a weired edge case if opreator are using both 2 and 3 and 3 get loaded before 2_

I've updated the readme file with some info about how this hook can be used. 


As for the priority. I think that's definitely a potential issue. I'm not sure how to fully avoid it, and perhaps it can't be avoided in all cases. Do you think it's worth warning about this in the readme? I've run into such edge cases in the past and it was hard to diagnose, but perhaps also hard to list all such edge cases.

2023-08-14 14:21 UTC, regisb commented on README.rst
> +	@FORUM_ENV.add()
minor: indentation looks weird from here

2023-08-14 14:22 UTC, regisb approved these changes
LGTM! Just a minor formatting issue

2023-08-15 04:56 UTC, xitij2000 commented on README.rst
> +	@FORUM_ENV.add()
Fixed, and added code highlighting as well.

2023-08-24 07:04 UTC, xitij2000 commented
> LGTM! Just a minor formatting issue

@regisb Just checking if this is OK to merge now.

2023-08-28 07:58 UTC, regisb approved these changes
LGTM! As the maintainer of this repo, I'll let @ghassanmas take care of squashing and merging.

2023-09-14 15:30 UTC, merged