feat: add COMPOSE_MOUNTS for cs_comments_service
overhangio/tutor-forum pull request #8
Opened 2022-07-20 19:14 UTC by Carlos-Muniz

Part of https://github.com/overhangio/2u-tutor-adoption/issues/26

In order to remove `runserver`, the following must be done for all official tutor plugins:

- [X] Ensure that the plugin is ported to the V1 API
- [ ] Ensure that the plugin hooks into the COMPOSE_MOUNTS filter in order to automatically bind-mount folders as appropriate.
- [X] Replace any references to runserver with start
- [X] Replace any references to the --volume option with an equivalent usage of the --mount option.

Within this repo, there was only one incomplete task: 'Ensure that the plugin hooks into the `COMPOSE_MOUNTS` filter in order to automatically bind-mount folders as appropriate.'. This task is solved with this PR.

A `COMPOSE_MOUNTS` function has been added to easily mount
`cs_comments_service` to `/app/cs_comments_service`

It was tested by installing the plugin and mounting a local `cs_comments_service` via `tutor dev run forum --mount=/path/to/cs_comments_service bash`, and checking that files changed or created within the container's bash shell could be found in the local `cs_comments_service` directory, and vice versa.

2022-07-20 19:14 UTC, Carlos-Muniz commented
@regisb @kdmccormick 
This is ready for review.

2022-07-20 19:37 UTC, kdmccormick approved these changes

2022-07-20 19:37 UTC, kdmccormick commented
cc @ghassanmas

2022-07-23 16:30 UTC, ghassanmas approved these changes
I tested this locally and it worked. 
I have tested this with `tutor local`. Just one note which I think isn't related to this patch rather `--mount` does it work same on `dev` vs `local`? on local I had to do remount when I changed files on host... may be its expected. 

Lastly just may be update Readme with the instuctions on how to do mounting, plus that when using mount, developer must install gems, i.e. `bundle install` otherwise forum service wont run.

2022-07-25 14:57 UTC, Carlos-Muniz commented on tutorforum/plugin.py
> +def _mount_cs_comments_service(volumes, name):
@regisb I've added a couple lines in the docs. Please let me know if any details are missing.

2022-07-25 14:59 UTC, ghassanmas requested changes

2022-07-25 14:59 UTC, ghassanmas commented on README.rst
> +
This is not possible since cs_comments_service in ruby not python. Also I would suggest to say something like make you install all gems in the targmet mount volume by running  `bundle install` or you can also to those lines in Docerfile https://github.com/overhangio/tutor-forum/blob/49d9a49d2544bc55ba61598ee7463c1a35352622/tutorforum/templates/forum/build/forum/Dockerfile#L27-L34

2022-07-25 15:10 UTC, Carlos-Muniz commented on README.rst
> +
Good catch, thanks @ghassanmas

2022-07-25 15:46 UTC, ghassanmas approved these changes

2022-07-25 15:47 UTC, ghassanmas commented on README.rst
> +
Approved again. looks good to my end. Thank you

2022-07-25 20:48 UTC, regisb approved these changes

2022-07-25 20:48 UTC, merged